apiVersion: v1
kind: Namespace
metadata:
  name: zeet
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeet-admin
  namespace: zeet
---
apiVersion: v1
kind: Secret
metadata:
  name: zeet-admin-token
  namespace: zeet
  annotations:
    kubernetes.io/service-account.name: zeet-admin
type: kubernetes.io/service-account-token