apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zeet-fine-grained
rules:
  - verbs: # read
      - get
      - list
      - watch
    apiGroups:
      - "*"
    resources:
      - "*"
  - verbs: # write
      - create
      - update
      - patch
      - delete
      - deletecollection
    apiGroups:
      - "" # core API group
    resources:
      - bindings
      - configmaps
      - endpoints
      - events
      - limitranges
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - podtemplates
      - replicationcontrollers
      - resourcequotas
      - secrets
      - serviceaccounts
      - services
  - verbs: # write
      - create
      - update
      - patch
      - delete
      - deletecollection
    apiGroups: # core-extension API group
      - apps
      - autoscaling
      - batch
      - policy
      - admissionregistration.k8s.io
      - apiextensions.k8s.io
      - apiregistration.k8s.io
      - authentication.k8s.io
      - authorization.k8s.io
      - certificates.k8s.io
      - coordination.k8s.io
      - discovery.k8s.io
      - events.k8s.io
      - flowcontrol.apiserver.k8s.io
      - metrics.k8s.io
      - networking.k8s.io
      - node.k8s.io
      - rbac.authorization.k8s.io
      - scheduling.k8s.io
      - storage.k8s.io
    resources:
      - "*"
  - verbs: # write
      - create
      - update
      - patch
      - delete
      - deletecollection
    apiGroups: # custom API group
      - acme.cert-manager.io
      - cert-manager.io
      - keda.sh
      - monitoring.coreos.com
      - monitoring.grafana.com
      - traefik.containo.us
      - traefik.io
    resources:
      - "*"
  - verbs: # write
      - create
      - update
      - patch
      - delete
      - deletecollection
    apiGroups: # AWS API group
      - crd.k8s.amazonaws.com
      - vpcresources.k8s.aws
      - elbv2
    resources:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zeet-fine-grained
subjects:
  - kind: ServiceAccount
    name: zeet-admin
    namespace: zeet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zeet-fine-grained
